---

- hosts: localhost
  connection: local
  gather_facts: yes

  vars_prompt:
    - name: "release_version"
      prompt: "Enter version number"
    - name: "release_product"
      prompt: "Enter product (SofTest|BuildingBlock|PrintX)"
    - name: "release_url"
      prompt: "Enter distributable binary url location"
    - name: "auth_required"
      prompt: "Artifactory authentication required? (true/false)"
      default: false

  tasks:
    - name: Download distributable binary
      get_url:
        url: "{{ release_url }}"
        tmp_dest: yes
      register: local_copy
      when: "{{ auth_required }} == false"
    
    - name: Include vault file if authentication required
      include_vars: vars/vault/secrets.yml
      when: "{{ auth_required }} == true"
    
    - name: Download authenticated distributable binary
      get_url:
        url: "{{ release_url }}"
        dest: .
        url_username: "{{ artifactory_username }}"
        url_password: "{{ artifactory_password }}"
      register: local_copy
      when: "{{ auth_required }} == true"

    - name: Update 
      s3:
        bucket: releases.examsoft.com
        mode: put
        object: /{{ release_product }}/{{ release_version }}/{{ release_product }}_{{ release_version }}.war
        src: "{{ local_copy.dest }}"
        permission: public-read
        overwrite: different
        # region shouldn't be needed but fix in the works
        # https://github.com/ansible/ansible-modules-core/pull/3347
        region: us-west-2

    - name: Delete local copy of distributable artifact
      file:
        state: absent
        path: "{{ local_copy.dest }}"
